#!/usr/bin/env node
/**
 * One-command deploy gate.
 *
 *   npm run ship                -- commit staged/unstaged code changes and push
 *   npm run ship -- "msg"       -- same, with your own commit message
 *   npm run ship -- --dry-run   -- run the full gate, then stop before committing
 *
 * Vercel auto-deploys from main, so pushing IS deploying. Everything below runs
 * before the push; if any step fails nothing is pushed.
 *
 * Never commits the local-only artifacts CLAUDE.md lists (ad folders, licence
 * scan, live-site snapshot).
 */
import { execSync, spawnSync } from 'node:child_process';

const EXCLUDE = [
  ':!adrevnview-ads',
  ':!matzop-ads',
  ':!.amdxb-live.html',
  ':!.license-page1.png',
];

const sh = (cmd, opts = {}) =>
  execSync(cmd, { stdio: 'pipe', encoding: 'utf8', ...opts }).trim();

const run = (label, cmd) => {
  process.stdout.write(`\n▸ ${label}\n`);
  const r = spawnSync(cmd, { shell: true, stdio: 'inherit' });
  if (r.status !== 0) {
    console.error(`\n✗ ${label} failed — nothing pushed.\n`);
    process.exit(r.status ?? 1);
  }
};

const argv = process.argv.slice(2);
const dryRun = argv.includes('--dry-run');
const messageArgs = argv.filter((a) => a !== '--dry-run');

// --- preflight -------------------------------------------------------------
const branch = sh('git rev-parse --abbrev-ref HEAD');
if (branch !== 'main') {
  console.error(`✗ On branch "${branch}". Deploys run from main; switch first.`);
  process.exit(1);
}

console.log('▸ Fetching origin');
try {
  sh('git fetch origin main');
} catch {
  console.error('✗ Could not reach origin. Check your network or `gh auth login`.');
  process.exit(1);
}

const behind = sh('git rev-list --count HEAD..origin/main');
if (behind !== '0') {
  console.error(
    `✗ ${behind} commit(s) on origin/main that you do not have.\n` +
      '  Run `git pull origin main` first so you do not clobber them.',
  );
  process.exit(1);
}

// --- quality gate ----------------------------------------------------------
run('Lint', 'npm run lint');
run('Typecheck', 'npx tsc --noEmit');
run('Test', 'npm test');
run('Build', 'npm run build');

// The build rewrites the CSP hash when the inline JSON-LD changes.
const cspDirty = sh('git status --porcelain -- vercel.json');
if (cspDirty) console.log('\n▸ CSP hash regenerated by the build — including it.');

if (dryRun) {
  console.log('\n✓ Dry run: gate passed. Nothing committed or pushed.\n');
  process.exit(0);
}

// --- commit ----------------------------------------------------------------
sh(`git add -A -- . ${EXCLUDE.join(' ')}`);

const staged = sh('git diff --cached --name-only');
const unpushed = sh('git rev-list --count origin/main..HEAD');

if (!staged && unpushed === '0') {
  console.log('\n✓ Nothing to ship — working tree clean and up to date with origin.\n');
  process.exit(0);
}

if (staged) {
  const message = messageArgs.join(' ').trim() || 'Update site content and fixes';
  const r = spawnSync('git', ['commit', '-m', message], { stdio: 'inherit' });
  if (r.status !== 0) {
    console.error('\n✗ Commit failed — nothing pushed.\n');
    process.exit(r.status ?? 1);
  }
  console.log(`\n▸ Committed: ${message}`);
} else {
  console.log(`\n▸ No new changes; pushing ${unpushed} existing commit(s).`);
}

// --- push (Vercel deploys from here) ---------------------------------------
run('Push to origin/main', 'git push origin main');

console.log(`
✓ Pushed. Vercel is building from main.
  Watch:  https://vercel.com/dashboard
  Repo:   ${sh('git remote get-url origin')}
`);
